version: "2026-02-16"
default_sector: "その他"
mappings:
  - edinet_name: "水産・農林業"
    internal_name: "水産・農林業"
    code: "0050"
  - edinet_name: "鉱業"
    internal_name: "鉱業"
    code: "1050"
  - edinet_name: "建設業"
    internal_name: "建設業"
    code: "2050"
  - edinet_name: "食料品"
    internal_name: "食料品"
    code: "3050"
  - edinet_name: "繊維製品"
    internal_name: "繊維製品"
    code: "3100"
  - edinet_name: "パルプ・紙"
    internal_name: "パルプ・紙"
    code: "3150"
  - edinet_name: "化学"
    internal_name: "化学"
    code: "3200"
  - edinet_name: "医薬品"
    internal_name: "医薬品"
    code: "3250"
  - edinet_name: "石油・石炭製品"
    internal_name: "石油・石炭製品"
    code: "3300"
  - edinet_name: "ゴム製品"
    internal_name: "ゴム製品"
    code: "3350"
  - edinet_name: "ガラス・土石製品"
    internal_name: "ガラス・土石製品"
    code: "3400"
  - edinet_name: "鉄鋼"
    internal_name: "鉄鋼"
    code: "3450"
  - edinet_name: "非鉄金属"
    internal_name: "非鉄金属"
    code: "3500"
  - edinet_name: "金属製品"
    internal_name: "金属製品"
    code: "3550"
  - edinet_name: "機械"
    internal_name: "機械"
    code: "3600"
  - edinet_name: "電気機器"
    internal_name: "電気機器"
    code: "3650"
  - edinet_name: "輸送用機器"
    internal_name: "輸送用機器"
    code: "3700"
  - edinet_name: "精密機器"
    internal_name: "精密機器"
    code: "3750"
  - edinet_name: "その他製品"
    internal_name: "その他製品"
    code: "3800"
  - edinet_name: "電気・ガス業"
    internal_name: "電気・ガス業"
    code: "4050"
  - edinet_name: "陸運業"
    internal_name: "陸運業"
    code: "5050"
  - edinet_name: "海運業"
    internal_name: "海運業"
    code: "5100"
  - edinet_name: "空運業"
    internal_name: "空運業"
    code: "5150"
  - edinet_name: "倉庫・運輸関連業"
    internal_name: "倉庫・運輸関連業"
    code: "5200"
  - edinet_name: "情報・通信業"
    internal_name: "情報・通信業"
    code: "5250"
  - edinet_name: "卸売業"
    internal_name: "卸売業"
    code: "6050"
  - edinet_name: "小売業"
    internal_name: "小売業"
    code: "6100"
  - edinet_name: "銀行業"
    internal_name: "銀行業"
    code: "7050"
  - edinet_name: "証券、商品先物取引業"
    internal_name: "証券、商品先物取引業"
    code: "7100"
  - edinet_name: "保険業"
    internal_name: "保険業"
    code: "7150"
  - edinet_name: "その他金融業"
    internal_name: "その他金融業"
    code: "7200"
  - edinet_name: "不動産業"
    internal_name: "不動産業"
    code: "8050"
  - edinet_name: "サービス業"
    internal_name: "サービス業"
    code: "9050"
